const constants = {
  ADD_TODO: 'ADD_TOD',
  REMOVE_TODO: 'REMOVE_TODO',
  ADD_TODO_ERROR: 'ADD_TODO_ERROR',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
  REGISTER:'REGISTER',
  REGISTER_ERROR:'REGISTER_ERROR',
  REGISTER_SUCCESS:'REGISTER_SUCCESS'
}

export default constants;